2025-08-17 22:25:22,820 ERROR: Exception on /api/projects/grw [DELETE] [in B:\IT\Web\test_task2\backend\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "B:\IT\Web\copy\backend\app\api\handlers.py", line 163, in delete_project
    db.session.delete(project)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\scoping.py", line 674, in delete
    return self._proxied.delete(instance)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\session.py", line 3542, in delete
    self._delete_impl(state, instance, head=True)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\session.py", line 3569, in _delete_impl
    cascade_states = list(
        state.manager.mapper.cascade_iterator("delete", state)
    )
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\mapper.py", line 3979, in cascade_iterator
    queue = deque(
        prop.cascade_iterator(
    ...<5 lines>...
        )
    )
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1526, in cascade_iterator
    tuples = self._value_as_iterable(
        state, dict_, self.key, passive=passive
    )
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1502, in _value_as_iterable
    for o in impl.get_collection(state, dict_, x, passive=passive)
             ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\writeonly.py", line 234, in get_collection
    history = self._get_collection_history(state, passive)
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\writeonly.py", line 404, in _get_collection_history
    return self.collection_history_cls(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, state, passive, apply_to=c
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\writeonly.py", line 94, in __init__
    raise exc.InvalidRequestError(
    ...<5 lines>...
    )
sqlalchemy.exc.InvalidRequestError: Attribute Floor.works can't load the existing state from the database for this operation; full iteration is not permitted.  If this is a delete operation, configure passive_deletes=True on the Floor.works relationship in order to resolve this error.
2025-08-17 22:25:32,138 INFO: Test task [in B:\IT\Web\copy\backend\app\__init__.py:31]
2025-08-17 22:25:34,856 ERROR: Exception on /api/projects/grw [DELETE] [in B:\IT\Web\test_task2\backend\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "B:\IT\Web\copy\backend\app\api\handlers.py", line 164, in delete_project
    db.session.commit()
    ~~~~~~~~~~~~~~~~~^^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\scoping.py", line 599, in commit
    return self._proxied.commit()
           ~~~~~~~~~~~~~~~~~~~~^^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<string>", line 2, in commit
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
    ~~~~~~~~~~~~~~~~~~^^
  File "<string>", line 2, in _prepare_impl
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
    ~~~~~~~~~~~~~~~~~~^^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\session.py", line 4353, in flush
    self._flush(objects)
    ~~~~~~~~~~~^^^^^^^^^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\session.py", line 4488, in _flush
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\session.py", line 4449, in _flush
    flush_context.execute()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 442, in execute
    postsort_actions = self._generate_actions()
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 400, in _generate_actions
    if action.execute(self):
       ~~~~~~~~~~~~~~^^^^^^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 532, in execute
    self.dependency_processor.presort_deletes(uow, delete_states)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\dependency.py", line 450, in presort_deletes
    history = uowcommit.get_attribute_history(
        state, self.key, self._passive_delete_flag
    )
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 283, in get_attribute_history
    history = impl.get_history(
        state,
    ...<3 lines>...
        | attributes.NO_RAISE,
    )
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\writeonly.py", line 380, in get_history
    c = self._get_collection_history(state, passive)
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\writeonly.py", line 404, in _get_collection_history
    return self.collection_history_cls(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, state, passive, apply_to=c
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\writeonly.py", line 94, in __init__
    raise exc.InvalidRequestError(
    ...<5 lines>...
    )
sqlalchemy.exc.InvalidRequestError: Attribute Object.works can't load the existing state from the database for this operation; full iteration is not permitted.  If this is a delete operation, configure passive_deletes=True on the Object.works relationship in order to resolve this error.
